// vue/src/App.vue
<script setup lang="ts">
import { EMAIL, RESUME_URL, about, contact, experience, hero, nav, skills, stats } from './data';
import { CURRENT, projects } from './projects';
import { Cmdline, PER_CHAR_BODY, PER_CHAR_HEADER, Typed } from './Typed';
import { useTheme } from './useTheme';

const { label, cycle } = useTheme();
const mailto = `mailto:${EMAIL}`;
</script>

<template>
  <div class="reveal go termbar">
    <div class="row">
      <div class="termbrand">
        <span class="dots"><span /><span /><span /></span>
        <span class="termtitle">angelo@scholze:~/resume$</span>
        <span class="projsw">
          <template v-for="p in projects" :key="p.id">
            <span v-if="p.id === CURRENT" class="sw is-active" aria-current="page">{{ p.label }}</span>
            <a v-else class="sw" :href="p.href">{{ p.label }}</a>
          </template>
        </span>
      </div>
      <nav class="termnav">
        <a v-for="n in nav" :key="n.href" :href="n.href">{{ n.label }}</a>
        <a :href="RESUME_URL" download>
          <button type="button" class="btn">download resume</button>
        </a>
        <button type="button" class="btn theme-toggle" @click="cycle">{{ label }}</button>
      </nav>
    </div>
  </div>

  <div class="wrap">
    <section class="hero">
      <Cmdline text="whoami" cursor />
      <Typed as="h1" :segs="[hero.name]" :per-char="PER_CHAR_HEADER" />
      <Typed as="p" class="role" :segs="[hero.role]" :per-char="PER_CHAR_HEADER" />
      <Typed as="p" class="sub" :segs="hero.sub" :per-char="PER_CHAR_BODY" />
      <div class="reveal go row">
        <a :href="RESUME_URL" download>
          <button type="button" class="btn">download resume.pdf</button>
        </a>
        <a :href="mailto">
          <button type="button" class="btn btn-outline">email me</button>
        </a>
      </div>
    </section>

    <hr class="rule" />

    <section class="status" aria-label="Angelo Scholze, by the numbers">
      <Cmdline text="stat --career" />
      <div class="reveal go grid">
        <div v-for="s in stats" :key="s.k">
          <p class="k">{{ s.k }}</p>
          <p :class="s.gilt ? 'v gilt' : 'v'">{{ s.v }}</p>
        </div>
      </div>
    </section>

    <hr class="rule" />

    <section id="about" class="about-full">
      <Cmdline text="cat about.md" />
      <Typed class="note" :segs="about" :per-char="PER_CHAR_BODY" />
    </section>

    <section id="experience" class="services">
      <Cmdline text="ls -la experience/" />
      <div class="list">
        <div v-for="e in experience" :key="e.name" class="entry">
          <div class="reveal go toprow">
            <span class="name">{{ e.name }}</span>
            <span class="dates">{{ e.dates }}</span>
          </div>
          <Typed :segs="e.body" :per-char="PER_CHAR_BODY" />
        </div>
      </div>
    </section>

    <section id="skills" class="skillsec">
      <Cmdline text="cat skills.txt" />
      <div class="reveal go chips">
        <span v-for="s in skills" :key="s" class="chip">{{ s }}</span>
      </div>
    </section>

    <hr class="rule" />

    <section id="contact" class="close">
      <Cmdline text="contact --me" />
      <Typed as="h3" :segs="['Get in touch']" :per-char="PER_CHAR_HEADER" />
      <div class="reveal go contactgrid">
        <div v-for="c in contact" :key="c.k" class="row2">
          <span class="k">{{ c.k }}</span>
          <a
            v-if="c.href"
            :href="c.href"
            :target="c.external ? '_blank' : undefined"
            :rel="c.external ? 'noopener' : undefined"
            >{{ c.label }}</a
          >
          <span v-else>{{ c.label }}</span>
        </div>
      </div>
      <div class="reveal go row">
        <a :href="RESUME_URL" download>
          <button type="button" class="btn">download resume.pdf</button>
        </a>
        <a :href="mailto">
          <button type="button" class="btn btn-outline">email me</button>
        </a>
      </div>
    </section>

    <footer class="reveal go">
      <span>angelo-scholze v1.0.0</span>
      <span class="ok">process exited 0</span>
    </footer>
  </div>
</template>

// react/src/App.tsx
import {
  EMAIL,
  RESUME_URL,
  about,
  contact,
  experience,
  hero,
  nav,
  skills,
  stats,
} from './data';
import { CURRENT, projects } from './projects';
import { Cmdline, PER_CHAR_BODY, PER_CHAR_HEADER, Typed } from './Typed';
import { useTheme } from './useTheme';

function DownloadButtons() {
  return (
    <div className="row reveal go">
      <a href={RESUME_URL} download>
        <button type="button" className="btn">
          download resume.pdf
        </button>
      </a>
      <a href={`mailto:${EMAIL}`}>
        <button type="button" className="btn btn-outline">
          email me
        </button>
      </a>
    </div>
  );
}

function ProjectSwitcher() {
  return (
    <span className="projsw">
      {projects.map((p) =>
        p.id === CURRENT ? (
          <span key={p.id} className="sw is-active" aria-current="page">
            {p.label}
          </span>
        ) : (
          <a key={p.id} className="sw" href={p.href}>
            {p.label}
          </a>
        ),
      )}
    </span>
  );
}

function Termbar() {
  const { label, cycle } = useTheme();
  return (
    <div className="termbar reveal go">
      <div className="row">
        <div className="termbrand">
          <span className="dots">
            <span />
            <span />
            <span />
          </span>
          <span className="termtitle">angelo@scholze:~/resume$</span>
          <ProjectSwitcher />
        </div>
        <nav className="termnav">
          {nav.map((n) => (
            <a key={n.href} href={n.href}>
              {n.label}
            </a>
          ))}
          <a href={RESUME_URL} download>
            <button type="button" className="btn">
              download resume
            </button>
          </a>
          <button type="button" className="btn theme-toggle" onClick={cycle}>
            {label}
          </button>
        </nav>
      </div>
    </div>
  );
}

export default function App() {
  return (
    <>
      <Termbar />
      <div className="wrap">
        <section className="hero">
          <Cmdline text="whoami" cursor />
          <Typed as="h1" segs={[hero.name]} perChar={PER_CHAR_HEADER} />
          <Typed as="p" className="role" segs={[hero.role]} perChar={PER_CHAR_HEADER} />
          <Typed as="p" className="sub" segs={hero.sub} perChar={PER_CHAR_BODY} />
          <DownloadButtons />
        </section>

        <hr className="rule" />

        <section className="status" aria-label="Angelo Scholze, by the numbers">
          <Cmdline text="stat --career" />
          <div className="grid reveal go">
            {stats.map((s) => (
              <div key={s.k}>
                <p className="k">{s.k}</p>
                <p className={s.gilt ? 'v gilt' : 'v'}>{s.v}</p>
              </div>
            ))}
          </div>
        </section>

        <hr className="rule" />

        <section className="about-full" id="about">
          <Cmdline text="cat about.md" />
          <Typed className="note" segs={about} perChar={PER_CHAR_BODY} />
        </section>

        <section className="services" id="experience">
          <Cmdline text="ls -la experience/" />
          <div className="list">
            {experience.map((e) => (
              <div key={e.name} className="entry">
                <div className="toprow reveal go">
                  <span className="name">{e.name}</span>
                  <span className="dates">{e.dates}</span>
                </div>
                <Typed segs={e.body} perChar={PER_CHAR_BODY} />
              </div>
            ))}
          </div>
        </section>

        <section className="skillsec" id="skills">
          <Cmdline text="cat skills.txt" />
          <div className="chips reveal go">
            {skills.map((s) => (
              <span key={s} className="chip">
                {s}
              </span>
            ))}
          </div>
        </section>

        <hr className="rule" />

        <section className="close" id="contact">
          <Cmdline text="contact --me" />
          <Typed as="h3" segs={['Get in touch']} perChar={PER_CHAR_HEADER} />
          <div className="contactgrid reveal go">
            {contact.map((c) => (
              <div key={c.k} className="row2">
                <span className="k">{c.k}</span>
                {c.href ? (
                  <a href={c.href} {...(c.external ? { target: '_blank', rel: 'noopener' } : {})}>
                    {c.label}
                  </a>
                ) : (
                  <span>{c.label}</span>
                )}
              </div>
            ))}
          </div>
          <DownloadButtons />
        </section>

        <footer className="reveal go">
          <span>angelo-scholze v1.0.0</span>
          <span className="ok">process exited 0</span>
        </footer>
      </div>
    </>
  );
}
